version: '2'

services:
  ### NGINX Server Container ##################################

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./www/sod-store:/var/www/sod-store
      - ./www/sod-cast:/var/www/sod-cast
      - ./www/sod-admin:/var/www/sod-admin
      - ./www/mytel:/var/www/mytel
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/h5bp:/etc/nginx/h5bp
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - frontend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
