version: '2'

services:
  ### NGINX Server Container ##################################

  nginx:
    build:
      context: ./nginx
    volumes:
      - /home/namtt/Projects/sod/sod-store-frontend/dist/store:/var/www/sod-store-frontend/dist/store
      - /home/namtt/Projects/sod/sod-store-frontend/dist/cast:/var/www/sod-store-frontend/dist/cast
      - /home/namtt/Projects/sod/sod-store-frontend/dist/admin:/var/www/sod-store-frontend/dist/admin
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/h5bp:/etc/nginx/h5bp
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - frontend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"